"""changed rating complaint to be one to one

Revision ID: 7cb584439f41
Revises: a1a291f4c0d8
Create Date: 2026-02-13 00:50:19.469153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cb584439f41'
down_revision: Union[str, Sequence[str], None] = 'a1a291f4c0d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ratings', ['complaint_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ratings', type_='unique')
    # ### end Alembic commands ###
